version: "3"

volumes:
  web-keys:
  db-data:


services:
  writefreely-web:
    container_name: "writefreely-web"
    image: "writeas/writefreely:latest"

    volumes:
      - "web-keys:/go/keys"
      - "./config.ini:/go/config.ini"

    ports:
      - "8080:8080"

    depends_on:
      - "writefreely-db"

    restart: unless-stopped

  writefreely-db:
    container_name: "writefreely-db"
    image: "mariadb:latest"
    volumes:
      - "db-data:/var/lib/mysql/data"

    environment:
      - MYSQL_DATABASE=writefreely
      - MYSQL_ROOT_PASSWORD=changeme
    ports:
      - "3306:3306"

    restart: unless-stopped